include:
  - template: Jobs/SAST.gitlab-ci.yml #semgrep tool
  - template: Jobs/SAST-IaC.gitlab-ci.yml #kicks tool

variables:
  GITLAB_ADVANCED_SAST_ENABLED: 'true'

stages:
  - build
  - test
  - runSCAScanUsingSnyk

run-sca-job:
    stage: runSCAScanUsingSnyk
    image: snyk/snyk:latest # Use the official Snyk Docker image
  script:
    - snyk auth $SNYK_TOKEN
    - snyk test --severity-threshold=high # Scan for open-source vulnerabilities with high severity
    - snyk monitor

my_github_triggered_job:
  stage: build
  script:  # Fixed: This was indented incorrectly
    - echo "This job runs when triggered by GitHub changes."
  rules:   # Fixed: This was indented incorrectly
    - if: '$CI_PIPELINE_SOURCE == "trigger"'