include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml

variables:
  DAST_WEBSITE: http://testphp.vulnweb.com
  DAST_FULL_SCAN_ENABLED: "true" 
  DAST_BROWSER_SCAN: "true"

stages:
  - build
  - test
  - deploy
  - dast
services:
  - docker:latest
image: docker:latest
docker-compose-build:
  stage: build
  script:
    - echo "Building services with Docker Compose..."
    - docker compose pull
    - docker compose up -d --build --force-recreate
    - echo "Services are up and running."
    - docker ps