include:
  - template: Jobs/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - deploy
services:
  - docker:latest
image: docker:latest
docker-compose-build:
  stage: build
  script:
    - echo "Building services with Docker Compose..."
    - docker compose up
    - echo "Services are up and running."
    - docker compose ps