#include:
#  - template: Jobs/SAST.gitlab-ci.yml #semgrep tool
#  - template: Jobs/SAST-IaC.gitlab-ci.yml #kicks tool

#variables:
#  GITLAB_ADVANCED_SAST_ENABLED: 'true'

stages:
  - build
  - test
  - runSCAScanUsingSnyk

# Move the Snyk scanning to a separate job with appropriate Node.js image
runSCAScanUsingSnyk:
  image: node:18
  script:
    - npm install -g snyk
    - snyk test

my_github_triggered_job:
  stage: build
  script:  # Fixed: This was indented incorrectly
    - echo "This job runs when triggered by GitHub changes."
  rules:   # Fixed: This was indented incorrectly
    - if: '$CI_PIPELINE_SOURCE == "trigger"'