#include:
#  - template: Jobs/SAST.gitlab-ci.yml #semgrep tool
#  - template: Jobs/SAST-IaC.gitlab-ci.yml #kicks tool

#variables:
#  GITLAB_ADVANCED_SAST_ENABLED: 'true'

stages:
  - build
  - test
  - runSCAScanUsingSnyk

# Move the Snyk scanning to a separate job with appropriate Node.js image
runSCAScanUsingSnyk:
  image: maven:3.8.5-openjdk-17-slim
  script:
    - SNYK_TOKEN='e601c0d5-e552-4814-9fb6-4b18418c3bd7'
    - export SNYK_TOKEN
    - mvn snyk:test

my_github_triggered_job:
  stage: build
  script:  # Fixed: This was indented incorrectly
    - echo "This job runs when triggered by GitHub changes."
  rules:   # Fixed: This was indented incorrectly
    - if: '$CI_PIPELINE_SOURCE == "trigger"'